name: Generate Bucket Terraform File

on:
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: 'Cloud Provider (AWS/GCP)'
        required: true
        default: 'GCP'
        options:
          - AWS
          - GCP
      customer_name:
        description: 'Customer Name'
        required: true

jobs:
  generate-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate Terraform File
      run: |
        cloud_provider="${{ github.event.inputs.cloud_provider }}"
        customer_name="${{ github.event.inputs.customer_name }}"
        
        if [ "$cloud_provider" == "AWS" ]; then
          file_name="customers/customer-$cloud_provider-$customer_name.tf"
          echo 'provider "aws" {' > $file_name
          echo '  region = "us-east-1"' >> $file_name
          echo '}' >> $file_name
          echo '' >> $file_name
          echo 'resource "aws_s3_bucket" "customer_bucket" {' >> $file_name
          echo "  bucket = \"customer-$customer_name\"" >> $file_name
          echo '  acl    = "private"' >> $file_name
          echo '}' >> $file_name

        elif [ "$cloud_provider" == "GCP" ]; then
          file_name="customers/customer-$cloud_provider-$customer_name.tf"
          echo 'resource "google_storage_bucket" "customer_bucket" {' > $file_name
          echo "  name     = \"customer-$customer_name\"" >> $file_name
          echo '  location = "us-central1"' >> $file_name
          echo '}' >> $file_name

        else
          echo "Invalid cloud provider selected"
          exit 1
        fi

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: "customer-${{ github.event.inputs.cloud_provider }}-${{ github.event.inputs.customer_name }}"
        title: "Generate Terraform file for ${{ github.event.inputs.cloud_provider }} bucket: customer-${{ github.event.inputs.cloud_provider }}-${{ github.event.inputs.customer_name }}.tf"
        body: "Automatically generated Terraform file for ${{ github.event.inputs.cloud_provider }} bucket: customer-${{ github.event.inputs.cloud_provider }}-${{ github.event.inputs.customer_name }}.tf"
