name: Generate Bucket Terraform File

on:
  workflow_dispatch:
    inputs:
      cloud_provider:
        description: 'Cloud Provider (AWS/GCP)'
        required: true
        default: 'GCP'
        options:
          - AWS
          - GCP
      customer_name:
        description: 'Customer Name'
        required: true

jobs:
  generate-terraform:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Generate Terraform File
      run: |
        cloud_provider="${{ github.event.inputs.cloud_provider }}"
        customer_name="${{ github.event.inputs.customer_name }}"
        
        if [ "$cloud_provider" == "AWS" ]; then
          file_name="customer-$cloud_provider-$customer_name.tf"
          content=$(cat <<- EOM
            provider "aws" {
              region = "us-east-1"
            }

            resource "aws_s3_bucket" "customer_bucket" {
              bucket = "customer-${customer_name}"
              acl    = "private"
            }
          EOM
          )
          echo "$content" > customers/$file_name

        elif [ "$cloud_provider" == "GCP" ]; then
          file_name="customer-$cloud_provider-$customer_name.tf"
          content=$(cat <<- EOM
            resource "google_storage_bucket" "customer_bucket" {
              name     = "customer-${customer_name}"
              location = "us-central1"
            }
          EOM
          )
          echo "$content" > customers/$file_name

        else
          echo "Invalid cloud provider selected"
          exit 1
        fi
      working-directory: ${{ github.workspace }}

    - name: Set Git identity
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"

    - name: Create Branch and Commit Changes
      run: |
        branch_name="customer-${{ github.event.inputs.cloud_provider }}-${{ github.event.inputs.customer_name }}"
        git checkout -b "$branch_name"
        git add customers/
        git commit -m "Generate Terraform file for $cloud_provider bucket: $file_name"
        git push origin "$branch_name"

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        base: main
        branch: "$branch_name"
        title: "Generate Terraform file for $cloud_provider bucket: $file_name"
        body: "Automatically generated Terraform file for $cloud_provider bucket: $file_name"
